BConway\WebsiteBundle\Document\Address:
  type: embeddedDocument
  fields:
    city:
      type: string
    geolocation:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\GeoLocation
    state:
      type: string
    streetAddress:
      type: string
    unit:
      type: string
    zip:
      type: string