BConway\WebsiteBundle\Document\StandardHours:
    type: embeddedDocument
    fields:
        mon:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        tue:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        wed:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        thu:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        fri:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        sat:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet
        sun:
            embedded: true
            type: many
            targetDocument: BConway\WebsiteBundle\Document\HourSet