BConway\WebsiteBundle\Document\StandardHours:
  type: embeddedDocument
  fields:
    mon:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    tue:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    wed:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    thu:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    fri:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    sat:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay
    sun:
      embedded: true
      type: one
      targetDocument: BConway\WebsiteBundle\Document\HoursDay